version: 2.1

executors:
  scala-executor:
    docker:
      - image: cimg/openjdk:21.0
    working_directory: ~/repo

commands:
  restore-sbt-cache:
    steps:
      - restore_cache:
          keys:
            - sbt-cache-v2-{{ checksum "build.sbt" }}
            - sbt-cache-v2-

  save-sbt-cache:
    steps:
      - save_cache:
          key: sbt-cache-v2-{{ checksum "build.sbt" }}
          paths:
            - ~/.ivy2/cache
            - ~/.sbt
            - ~/.cache/coursier

jobs:

  quality:
    executor: scala-executor
    steps:
      - checkout
      - restore-sbt-cache
      - run:
          name: Scalafmt check
          command: sbt scalafmtCheckAll
      - run:
          name: Scalafix check
          command: sbt "scalafixAll --check"
      - save-sbt-cache

  build-and-test:
    executor: scala-executor
    steps:
      - checkout
      - restore-sbt-cache
      - run:
          name: Compile
          command: sbt -v compile
      - run:
          name: Run unit tests
          command: sbt -v test
      - save-sbt-cache

  integration-tests:
    executor: scala-executor

    environment:
      SBT_OPTS: "-Xmx2G"

    steps:
      - checkout
      - restore-sbt-cache

      # Provision a real Docker daemon for Testcontainers
      - setup_remote_docker: {}

      # Optional but useful for debugging
      - run:
          name: Docker info
          command: docker info

      - run:
          name: Run integration tests
          command: sbt -v It/test

      - save-sbt-cache

workflows:
  build:
    jobs:
      - quality
      - build-and-test:
          requires:
            - quality
      - integration-tests:
          requires:
            - build-and-test
